#-- Lattice Semiconductor Corporation Ltd.
#-- Map run script generated by Radiant

set ret 0
if {[catch {

if {![file exists {C:/Users/llemos/Documents/GitHub/E155-uP-labs/lab2_ll_two_displays/AI prototype/lab2_ll_ai_prototype/impl_1}]} {
  file mkdir {C:/Users/llemos/Documents/GitHub/E155-uP-labs/lab2_ll_two_displays/AI prototype/lab2_ll_ai_prototype/impl_1}
}
cd {C:/Users/llemos/Documents/GitHub/E155-uP-labs/lab2_ll_two_displays/AI prototype/lab2_ll_ai_prototype/impl_1}

sys_set_attribute -gui on -msg {C:/Users/llemos/Documents/GitHub/E155-uP-labs/lab2_ll_two_displays/AI prototype/lab2_ll_ai_prototype/promote.xml}
msg_load {C:/Users/llemos/Documents/GitHub/E155-uP-labs/lab2_ll_two_displays/AI prototype/lab2_ll_ai_prototype/promote.xml}
des_set_project_udb -in {lab2_ll_ai_prototype_impl_1_syn.udb} -out {lab2_ll_ai_prototype_impl_1_map.udb} -milestone map -pm ice40tp
des_set_reference_udb -clean
# map option
map_set_option { report_symbol_cross_reference false report_signal_cross_reference false   ignore_constraint_errors false}
map_run

} out]} {
   puts $out
   set ret 1
}
exit -force ${ret}
